### ISSUE TITLE
Cannot parse css when rendered with the hugo command

### ISSUE THREAD

**Issue by owl4ce** [your-identity/hugo-theme-dimension#1]
Hello, sir. I found the bug cannot load css when rendered using the hugo command, after I searched it was necessary to add quotation marks in this **href** to _layouts/partials/header.html_

```
 <link rel="stylesheet" href={{ "assets/css/main.css" | absURL }}/>
 <noscript><link rel="stylesheet" href={{ "assets/css/noscript.css" | absURL }}/></noscript>
```
to
```
<link rel="stylesheet" href="{{ "assets/css/main.css" | absURL }}"/>
<noscript><link rel="stylesheet" href="{{ "assets/css/noscript.css" | absURL }}"/></noscript>
```

### Before
![Before](https://user-images.githubusercontent.com/53987136/82515404-56862480-9b42-11ea-827b-523d06f48bc3.png)

### After Fix
![After](https://user-images.githubusercontent.com/53987136/82515401-538b3400-9b42-11ea-8d64-760052b0809f.png)

By the way, the theme is good! :100:

**Comment by your-identity** [comment]
Thank you for your help @owl4ce, I addressed this suggestion in https://github.com/your-identity/hugo-theme-dimension/commit/1a8785e0fa8200f1b0450f568dcae7e728c04f2e please let me know if this solves the issue and I'll close it.
