### ISSUE TITLE
Other `fa-icons` Do Not Work

### ISSUE THREAD

**Issue by JustinTimperio** [your-identity/hugo-theme-dimension#3]
This is quite similar to #2 but in my case, the only icons that work are 'gem' and 'flag'.

I have tried:
1. Calling the icon with `fa-<icon-name>` (Results in an empty circle)

2. Opening the page in another browser, clearing caches, and digging through source.

All the icons that are available render like this.

![Broken fa-icon](https://user-images.githubusercontent.com/9936997/86063450-e750f980-ba38-11ea-9a85-15ffa1944d8d.png)

To reproduce, create a new site, setup the theme, etc, etc. Once set up, select any icon other than 'flag' or 'gem'.

Tested On:
Chromium
Firefox
Hugo V0.60.0 and V0.73

**Comment by asclines** [comment]
It appears only Font Awesome Regular icons work.

So basically this list: https://fontawesome.com/icons?d=gallery&s=regular&m=free

**Comment by hexdae** [comment]
Thank you @asclines, the icons are limited to the Font Awesome Regular set, due to licensing constraints. @JustinTimperio  if you are ok with this, I'll close the issue

**Comment by JustinTimperio** [comment]
Thanks @asclines and @d-asnaghi! I did try this and the icons in the regular set do seem to work. You can feel free to close this issue. It might be helpful though to add plug and play support for those who own the icon pack. I have tried dropping the premium pack in its typical directory and the icons seem to not be "importing"/referenceable.

**Comment by notcarbide** [comment]
I'm able to use brand FontAwesome icons just fine by using something like `class="fab fa-github"`. It seems the icons are now split into different groups by default. Just gotta find the class for the category of icon you want.

**Comment by hexdae** [comment]
I ended up abandoning font awesome entirely. Let me know if the new PR works for this feature request

**Comment by hexdae** [comment]
I am going to close this issue since it was addressed in #16
