### ISSUE TITLE
Feature Request: Remove Icon/Logo UI Element

### ISSUE THREAD

**Issue by JustinTimperio** [your-identity/hugo-theme-dimension#4]
It would be really helpful if it was possible to remove the whole icon element. That's really all.

The original docs seem to reference this ability. 
https://github.com/dspechnikov/dimension-hugo/blob/master/documentation.md#supported-site-parameters

**Comment by hexdae** [comment]
PR https://github.com/your-identity/hugo-theme-dimension/pull/7 is out to address your request. @JustinTimperio let me know if this works for you.

To remove the icon simply delete the corresponding line in your YAML config for the page

**Comment by JustinTimperio** [comment]
Awesome, thanks for the patch here! I will check this out later. I will close this feature request now.
