### ISSUE TITLE
Chinese title cannot be parsed

### ISSUE THREAD

**Issue by lostmaniac** [your-identity/hugo-theme-dimension#5]
The Chinese title cannot be parsed, the article is not displayed, and can it support custom URLs?

E.g

```
---
title: 玩客云
description: "A collection of posts"
icon: "flag"
url: wankeyun
---

范德萨范德萨

```

Prevent Chinese characters

**Comment by hexdae** [comment]
HI @MSG-maniac, thanks for raising this. To keep backward compatibility I decided to `base64Encode` unicode chars. Hope this fixes your problem. PR https://github.com/your-identity/hugo-theme-dimension/pull/6


Here is a demo of the Fix:


![ezgif-7-cf373ebf7551](https://user-images.githubusercontent.com/30296575/89129044-f0196d00-d4c7-11ea-9dd6-c62e4a77acbf.gif)

**Comment by lostmaniac** [comment]
Thank you very much for your fix bug
